extends:
  - eslint:recommended
  - plugin:solid/recommended

parserOptions:
  ecmaVersion: 2022

plugins:
  - prettier
  - solid

env:
  browser: true
  es6: true
  webextensions: true

rules:
  no-unused-vars:
    - error
    - ignoreRestSiblings: true
      varsIgnorePattern: '^_'
      argsIgnorePattern: '^_'
